/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import Logica.Facade;
import Logica.MyURL;
import SpiderEngine.*;
import Spiderbot.MySpiderBot;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import org.apache.tika.exception.TikaException;
import org.xml.sax.SAXException;
import xmlreader.*;

/**
 *
 * @author Gabo
 */
public class VentanaSpider extends javax.swing.JFrame {
    private Facade _manager;
    private String _nuevoURL;
    /**
     * Creates new form VentanaSpider
     */
    private  MySpiderBot _spiderBot;
    private MySpiderBot _nuevo;
    public VentanaSpider(Facade pNanager) {
        initComponents();
        try {
            _manager=new Facade();
        } catch (IOException ex) {
            Logger.getLogger(VentanaSpider.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(VentanaSpider.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        _inicializarBot = new javax.swing.JToggleButton();
        _indiceBot = new javax.swing.JToggleButton();
        _urlNuevo = new javax.swing.JTextField();
        insertarBoton = new javax.swing.JButton();
        _botonXML = new javax.swing.JButton();
        _textoXML = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("SpiderBot");

        _inicializarBot.setText("Inicializar");
        _inicializarBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _inicializarBotActionPerformed(evt);
            }
        });

        _indiceBot.setText("Generar Indice");
        _indiceBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _indiceBotActionPerformed(evt);
            }
        });

        insertarBoton.setText("Insertar URL");
        insertarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarBotonActionPerformed(evt);
            }
        });

        _botonXML.setText("Insertar XML");
        _botonXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _botonXMLActionPerformed(evt);
            }
        });

        _textoXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _textoXMLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_textoXML, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertarBoton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(_botonXML, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(87, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_inicializarBot, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(_indiceBot))
                            .addComponent(_urlNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(_textoXML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_botonXML)
                .addGap(23, 23, 23)
                .addComponent(_urlNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insertarBoton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_inicializarBot, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_indiceBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _inicializarBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__inicializarBotActionPerformed
        // TODO add your handling code here:
        
       
        try {
        _nuevo=new MySpiderBot(new Facade());
        _nuevo.configurarVariables();
        _nuevo.encolarURL("MyURLXML.xml");
        
        _nuevo.crearHilos();
            
        } catch (IOException ex) {
            Logger.getLogger(VentanaSpider.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(VentanaSpider.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event__inicializarBotActionPerformed

    private void _indiceBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__indiceBotActionPerformed
        try {
            _nuevo.generarXML();
            JOptionPane.showMessageDialog(null, "XML GENERADO");
            System.exit(0);
        } catch (IOException ex) {
            Logger.getLogger(VentanaSpider.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TikaException ex) {
            Logger.getLogger(VentanaSpider.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(VentanaSpider.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event__indiceBotActionPerformed

    private void insertarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarBotonActionPerformed
        // TODO add your handling code here:
        this._nuevoURL=this._urlNuevo.getText();
        _nuevo.getColaURL().enqueue(new MyURL(_nuevoURL));
        
        this._urlNuevo.setText("");
    }//GEN-LAST:event_insertarBotonActionPerformed

    private void _textoXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__textoXMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__textoXMLActionPerformed

    private void _botonXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__botonXMLActionPerformed
        // TODO add your handling code here:
        try{
            _nuevo.encolarURL(this._textoXML.getText());
        this._textoXML.setText("");
            
            
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, "DIRECCION INVALIDA");
        this._textoXML.setText("");
            
        }
        
    }//GEN-LAST:event__botonXMLActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _botonXML;
    private javax.swing.JToggleButton _indiceBot;
    private javax.swing.JToggleButton _inicializarBot;
    private javax.swing.JTextField _textoXML;
    private javax.swing.JTextField _urlNuevo;
    private javax.swing.JButton insertarBoton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
